"""initial migration

Revision ID: e73739d01ba0
Revises: 
Create Date: 2025-02-14 18:31:50.204202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e73739d01ba0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_activities', schema=None) as batch_op:
        batch_op.create_unique_constraint('_name_group_uc', ['name', 'group_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_activities', schema=None) as batch_op:
        batch_op.drop_constraint('_name_group_uc', type_='unique')

    # ### end Alembic commands ###
